"""Change in oauth token model

Revision ID: 104c85135682
Revises: ef050afc22bd
Create Date: 2026-06-06 15:13:34.224576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '104c85135682'
down_revision: Union[str, None] = 'ef050afc22bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    op.alter_column('oauth_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
