"""Initial Migration

Revision ID: ef050afc22bd
Revises: 
Create Date: 2026-06-04 17:18:18.397284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ef050afc22bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('email_sync_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('history_id', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_sync_states_user_id'), 'email_sync_states', ['user_id'], unique=False)
    op.create_table('emails',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_action_required', sa.Boolean(), nullable=True),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_index('ix_emails_classification', 'emails', ['classification'], unique=False)
    op.create_index('ix_emails_gmail_message_id', 'emails', ['gmail_message_id'], unique=True)
    op.create_index('ix_emails_gmail_thread_id', 'emails', ['gmail_thread_id'], unique=False)
    op.create_index('ix_emails_priority_score', 'emails', ['priority_score'], unique=False)
    op.create_index('ix_emails_received_at', 'emails', ['received_at'], unique=False)
    op.create_index('ix_emails_sender_email', 'emails', ['sender_email'], unique=False)
    op.create_index('ix_emails_user_id', 'emails', ['user_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_table('email_classification_audits',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('classification_method', sa.String(length=100), nullable=False),
    sa.Column('classification_result', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_classification_audits_email_id', 'email_classification_audits', ['email_id'], unique=False)
    op.create_table('interviews',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interviews_company', 'interviews', ['company'], unique=False)
    op.create_index(op.f('ix_interviews_email_id'), 'interviews', ['email_id'], unique=False)
    op.create_index('ix_interviews_interview_date', 'interviews', ['interview_date'], unique=False)
    op.create_table('job_opportunities',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('apply_link', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_opportunities_company', 'job_opportunities', ['company'], unique=False)
    op.create_index('ix_job_opportunities_deadline', 'job_opportunities', ['deadline'], unique=False)
    op.create_index('ix_job_opportunities_email_id', 'job_opportunities', ['email_id'], unique=False)
    op.create_index('ix_job_opportunities_role', 'job_opportunities', ['role'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_email_id'), 'processing_jobs', ['email_id'], unique=False)
    op.create_index('ix_processing_jobs_pipeline_stage', 'processing_jobs', ['pipeline_stage'], unique=False)
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_email_id'), 'tasks', ['email_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_email_id'), table_name='tasks')
    op.drop_index('ix_tasks_due_date', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_processing_jobs_status', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_pipeline_stage', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_email_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_job_opportunities_role', table_name='job_opportunities')
    op.drop_index('ix_job_opportunities_email_id', table_name='job_opportunities')
    op.drop_index('ix_job_opportunities_deadline', table_name='job_opportunities')
    op.drop_index('ix_job_opportunities_company', table_name='job_opportunities')
    op.drop_table('job_opportunities')
    op.drop_index('ix_interviews_interview_date', table_name='interviews')
    op.drop_index(op.f('ix_interviews_email_id'), table_name='interviews')
    op.drop_index('ix_interviews_company', table_name='interviews')
    op.drop_table('interviews')
    op.drop_index('ix_email_classification_audits_email_id', table_name='email_classification_audits')
    op.drop_table('email_classification_audits')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index('ix_emails_user_id', table_name='emails')
    op.drop_index('ix_emails_sender_email', table_name='emails')
    op.drop_index('ix_emails_received_at', table_name='emails')
    op.drop_index('ix_emails_priority_score', table_name='emails')
    op.drop_index('ix_emails_gmail_thread_id', table_name='emails')
    op.drop_index('ix_emails_gmail_message_id', table_name='emails')
    op.drop_index('ix_emails_classification', table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_email_sync_states_user_id'), table_name='email_sync_states')
    op.drop_table('email_sync_states')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
